### ISSUE TITLE
MLAT Server Direct 

### ISSUE THREAD

**Issue by marknfischer** [wiedehopf/combine1090#3]
MLAT server has an output of Basestation for local port mapping on server (a natural place to listen for results).  Combine1090 has a limitation of Beast (from what I can tell).  Is there a best practice for routing MLAT data to combine1090?  Does it need to go back through receivers as the only path or is there a way to route direct from MLAT server that I am missing?

**Comment by wiedehopf** [comment]
Just use readsb if you're running mlat-server.
It has the --net-connector argument .... you can connect to whatever.
 https://github.com/wiedehopf/readsb

combine1090 was thrown together quite some time ago when there was no such capability.
It continues to exist for people who can't compose their own command line.
Running mlat-server hopefully means you are able to do that.

**Comment by fatihyucesoy** [comment]
Hi Wiedehopf,

Can you give a little bit more information on the MLAT server installation and how it will be with 3 different antennas? 


BR


> Just use readsb if you're running mlat-server. It has the --net-connector argument .... you can connect to whatever. https://github.com/wiedehopf/readsb
> 
> combine1090 was thrown together quite some time ago when there was no such capability. It continues to exist for people who can't compose their own command line. Running mlat-server hopefully means you are able to do that.

**Comment by wiedehopf** [comment]
4 receivers at least.
1km from each of the other 3 receivers.

This is the readme: https://github.com/wiedehopf/mlat-server

mlat-server --help

Really just use adsb.lol or airplanes.live and use the mlat-results from the mlat-client output.
Otherwise, read --help and if necessary the source code to figure out how to run mlat-server.

**Comment by fatihyucesoy** [comment]
I am trying to create my own mlat server. But I am having trouble installing mlat server. I would like to ask for your help with the Python part.

**Comment by wiedehopf** [comment]
You are not even asking a question.

What do you expect as an answer?

"I need help" is not useful.

But really if you can't manage to run it that's not my problem.
So maybe i answer maybe i don't.
But really just ask instead of dancing around it.
That helps no one.

Read this please:
https://metaquestion.net/
